version: '3.8'
services:
  db-test:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kilimo_test
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_test_data:
